spring:
  profiles:
    active: prod
  application:
    name: "ordermircroservice"
  data:
    mongodb:
      uri: mongodb://root:1234@mongodb:27017/ordermicroservice?authSource=admin
      host: root
      password: 1234
      database: ordermicroservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://mysql:3306/orderMicroService?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka.support.serializer: WARN
    io.confluent.kafka.serializers: WARN
    org.apache.avro: WARN