spring:
  application:
    name: "ordermircroservice"
  data:
    mongodb:
      uri: mongodb://root:1234@mongodb:27017/ordermicroservice?authSource=admin
      host: root
      password: 1234
      database: ordermicroservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://mysql:3306/orderMicroService?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8


logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka.support.serializer: DEBUG
    io.confluent.kafka.serializers: DEBUG
    org.apache.avro: WARN