POST http://localhost:8080/gateway/service/createOrder
Content-Type: application/json

{
  "orderRequest": {
    "userId": "raonpark",
    "products": [
      {
        "name": "Coca Cola",
        "quantity": 3,
        "price": 2300
      },
      {
        "name": "Coffee Maker",
        "quantity": 1,
        "price": 310000
      }
    ],
    "sellerId": "1"
  },
  "paymentRequest": {
    "amount": 316900,
    "paymentType": "신용카드",
    "cardNumber": "283-182-3728-38",
    "cardCvc": "232"
  }
}